apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-initdb
  namespace: mongodb
data:
  mongo-init.js: |
    use scrapper;
    db.createUser(
        {
            user: "scrapper",
            pwd: "123456",
            roles: [
                {
                    role: "readWrite",
                    db: "scrapper"
                }
            ]
        }
    );
