apiVersion: v1
kind: Namespace
metadata:
  name: search
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: search
  labels:
    name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      name: search
  template:
    metadata:
      labels:
        name: search
    spec:
      containers:
        - name: search
          env:
            - name: ELASTICSEARCH_URI
              value: http://elasticsearch.elasticsearch.svc.cluster.local:9200
            - name: RABBITMQ_URI
              value: amqp://rabbitmq.rabbitmq.svc.cluster.local:5672
          image: ghcr.io/comments-finder/search:release_v0.0.19 # {"$imagepolicy": "flux-system:search"}
          ports:
            - containerPort: 3333
          resources:
            limits:
              cpu: "0.1"
              memory: 5000Mi
            requests:
              cpu: "0.05"
              memory: 100Mi
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: search
spec:
  selector:
    name: search
  ports:
    - name: http
      port: 3333
      targetPort: 3333
  type: ClusterIP
