apiVersion: v1
kind: Namespace
metadata:
  name: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: ui
  labels:
    name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ui
  template:
    metadata:
      labels:
        name: ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/comments-finder/ui:release_v0.0.18 # {"$imagepolicy": "flux-system:ui"}
          env:
            - name: SEARCH_URL
              value: http://search.search.svc.cluster.local:3333
          ports:
            - containerPort: 1000
          resources:
            limits:
              cpu: "0.1"
              memory: 500Mi
            requests:
              cpu: "0.05"
              memory: 100Mi
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: ui
spec:
  selector:
    name: ui
  ports:
    - name: http
      port: 1000
      targetPort: 1000
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router
  namespace: ui
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '300'
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: 1000
