apiVersion: v1
kind: Namespace
metadata:
  name: search
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: search
  labels:
    name: search
spec:
  replicas: 2
  selector:
    matchLabels:
      name: search
  template:
    metadata:
      labels:
        name: search
    spec:
      containers:
        - name: search
          image: ghcr.io/comments-finder/search:release_v0.0.1 # {"$imagepolicy": "flux-system:search"}
          ports:
            - containerPort: 1000
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
            requests:
              cpu: "0.05"
              memory: 50Mi
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: search
spec:
  selector:
    name: search
  ports:
    - name: http
      port: 1000
      targetPort: 1000
  type: NodePort
