apiVersion: v2
name: helm
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: mongodb
    version: "13.9.0"
    repository: "https://charts.bitnami.com/bitnami"

